name: Check and Test
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: install-ubuntu
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash
          echo "$HOME/.moon/bin" >> $GITHUB_PATH
      - name: install-windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser; irm https://cli.moonbitlang.com/install/powershell.ps1 | iex
          "C:\Users\runneradmin\.moon\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: post install
        run: |
          moon version --all
          moon update

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Setup wasmtime
        uses: jcbhmr/setup-wasmtime@v2

      - name: moon check & test
        run: |
          moon check
          moon test

      - name: e2e test
        run: |
          deno task test:build
          deno task test

      - name: lint
        run: |
          moon fmt && git diff --exit-code
          moon info && git diff --exit-code

